main.py: Running...
Processing foo...
   All good...
Processing add_to_foreign...
   All good...
Processing add_foreign_node...
   Got an exception: raised LANGKIT_SUPPORT.ERRORS.PROPERTY_ERROR : errors occurred in Populate_Lexical_Env
Processing add_foreign_md...
   Got an exception: raised LANGKIT_SUPPORT.ERRORS.PROPERTY_ERROR : errors occurred in Populate_Lexical_Env
main.py: Done.
Done
