main.py: Running...
Running PLE...
   PropertyError: errors occurred in Populate_Lexical_Env
main.py: Done.
Done
