main.py: Running...
== foo ==
   All good...

== add_to_foreign ==
   Got a PropertyError: errors occurred in Populate_Lexical_Env

main.py: Done.
Done
